name: hexo template

on: [push]  # 在 push 时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 运行在最新版的 ubuntu

    steps:
    - uses: actions/checkout@v2.0.0  # 拉取仓库代码
    - name: checkout submodules  # 获取 git 子模块 用来拉取主题仓库
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    
    - uses: borales/actions-yarn@v2.0.0  # 使用 yarn 安装依赖
      with:
        cmd: install
        
    - name: generate public  # 生成静态页 hexo generate
      run: npm run build
    
    - name: deploy  # 部署到仓库 gh-pages 分支
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
